#!/bin/sh
#
# Start the example_c....
#

case "$1" in
  start)
	printf "Starting example_c: "
	/usr/bin/example_c &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping example_c: "
	
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

