#!/bin/sh

# 探测 Slot
if grep -q "root=/dev/vda2" /proc/cmdline; then
    MY_SELECTION="copy_to_b"
else
    MY_SELECTION="copy_to_a"
fi

# 动态生成配置文件
# cat << EOF > /etc/swupdate.cfg
# globals :
# {
#     verbose = true;
#     loglevel = 5;
# };

# software-selections :
# {
#     stable = "$MY_SELECTION";
# };

# webserver :
# {
#     document_root = "/var/www/swupdate";
#     port = 8080;
# };
# EOF

# SWUPDATE_ARGS="-f /etc/swupdate.cfg"
# SWUPDATE_WEBSERVER_ARGS=""

SWUPDATE_ARGS="${SWUPDATE_ARGS} -e stable,${MY_SELECTION}"
SWUPDATE_EXTRA_ARGS="${SWUPDATE_EXTRA_ARGS} -e stable,${MY_SELECTION}"
SWUPDATE_WEBSERVER_ARGS="-r /var/www/swupdate -p 8080"
